version: "3.9"

networks:
  driver-csilli:
    driver: bridge

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "rootpasswordforlocaldev"
      MYSQL_DATABASE: "csilliadb"
    volumes:
      - ./data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - driver-csilli
